name = "elden-ring-map-router"
main = "worker.js"
compatibility_date = "2024-09-23"

[vars]
PAGES_ORIGIN = "https://elden-ring-3d-map.pages.dev"

# Route both the bare path and all subpaths to this worker
[[routes]]
pattern = "stevenpg.com/projects/map/eldenring"
zone_name = "stevenpg.com"

[[routes]]
pattern = "stevenpg.com/projects/map/eldenring/*"
zone_name = "stevenpg.com"
